Repository AGH-Wstep-do-Informatyki-2022-2023/klad-Alethinophidia-tow, pull requests merged in 2022-12, with the labels that each got.

#10 pull_request_Seby
  Plansza_i_Pacman.py
  assets/images/Pacman.png
Labels: bug, help wanted

#17 Update README.md
  README.md
Labels: documentation

#12 Add files via upload
  Board.py
Labels: grafika
